server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

grpc:
  server:
    port: 8082

spring:
  messages:
    fallback-to-system-locale: true
    encoding: UTF-8
    basename: i18n/messages